# -*- coding: utf-8 -*-
"""Diploma.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NUJskPBYWLwvL7SJXtA5UBhThK1_2fph
"""

!pip install -q unsloth trl peft accelerate bitsandbytes datasets

from google.colab import drive
drive.mount('/content/drive')

import json

DATA_PATH = "/content/drive/MyDrive/datasets/final_dataset.json"

with open(DATA_PATH, "r", encoding="utf-8") as f:
    data = json.load(f)

print(f" Загружено примеров: {len(data)}")
print("Пример:", data[0])

from unsloth import FastLanguageModel
import torch

model_name = "unsloth/Phi-3-mini-4k-instruct-bnb-4bit"
max_seq_length = 2048

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=model_name,
    max_seq_length=max_seq_length,
    load_in_4bit=True,
)

print(" Модель загружена")

from datasets import Dataset

def format_chat(example):
    return tokenizer.apply_chat_template(
        example["messages"],
        tokenize=False,
        add_generation_prompt=False
    )

formatted_texts = [format_chat(x) for x in data]

dataset = Dataset.from_dict({"text": formatted_texts})

print(" Пример после форматирования:\n")
print(formatted_texts[0][:500])

def tokenize_function(examples):
    return tokenizer(
        examples["text"],
        truncation=True,
        max_length=max_seq_length,
    )

dataset = dataset.map(
    tokenize_function,
    batched=True,
    num_proc=2,
)

dataset_split = dataset.train_test_split(test_size=0.05, seed=42)

train_dataset = dataset_split["train"]
eval_dataset = dataset_split["test"]

print(f"Train: {len(train_dataset)}")
print(f"Eval: {len(eval_dataset)}")

model = FastLanguageModel.get_peft_model(
    model,
    r=16,  #
    target_modules=[
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj",
    ],
    lora_alpha=32,
    lora_dropout=0,
    bias="none",
    use_gradient_checkpointing="unsloth",
)

from transformers import TrainingArguments

OUTPUT_DIR = "/content/drive/MyDrive/phi3_finetune"

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,

    per_device_train_batch_size=2,
    gradient_accumulation_steps=4,

    num_train_epochs=2,
    learning_rate=2e-4,

    logging_steps=10,
    save_strategy="steps",
    save_steps=100,
    save_total_limit=3,

    eval_strategy="steps",
    eval_steps=50,

    fp16=not torch.cuda.is_bf16_supported(),
    bf16=torch.cuda.is_bf16_supported(),

    optim="adamw_8bit",
    weight_decay=0.01,
    lr_scheduler_type="linear",

    report_to="none",
)

from trl import SFTTrainer

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    dataset_text_field="text",
    max_seq_length=max_seq_length,
    args=training_args,
)

trainer.train()

model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

model.save_pretrained_gguf(
    "/content/drive/MyDrive/phi3_gguf",
    tokenizer,
    quantization_method="q4_k_m"
)