# -*- coding: utf-8 -*-
"""DiplomaTestsipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1micOlU08DsH5ngXwqJLB41rmIwH6TNQ4
"""

!pip install -q unsloth

from google.colab import drive
drive.mount('/content/drive')

import json

with open("/content/drive/MyDrive/course_lora/adapter_config.json") as f:
    json.load(f)

# запуск курсовой модели
from unsloth import FastLanguageModel
from peft import PeftModel
import torch

# 1. Загружаем базовую модель
model, tokenizer = FastLanguageModel.from_pretrained(
    "unsloth/Phi-3-mini-4k-instruct-bnb-4bit",
    max_seq_length=2048,
    load_in_4bit=True,
)

# 2. Подключаем твой LoRA адаптер (ВАЖНО: путь к папке, не к checkpoint)
model = PeftModel.from_pretrained(
    model,
    "/content/drive/MyDrive/course_lora"
)

# 3. Режим инференса
FastLanguageModel.for_inference(model)

# запуск дообученной модели 1
from unsloth import FastLanguageModel
from peft import PeftModel
import torch

# 1. Загружаем базовую модель
model, tokenizer = FastLanguageModel.from_pretrained(
    "unsloth/Phi-3-mini-4k-instruct-bnb-4bit",
    max_seq_length=2048,
    load_in_4bit=True,
)

# 2. Подключаем твой LoRA адаптер (ВАЖНО: путь к папке, не к checkpoint)
model = PeftModel.from_pretrained(
    model,
    "/content/drive/MyDrive/phi3_finetune"
)

# 3. Режим инференса
FastLanguageModel.for_inference(model)

# точно рабочий вариант для тестирования по одному запросу

messages = [
    {"role": "user", "content": "Напиши текст в публицистическом стиле. Тема: Глобальное потепление"}
]

inputs = tokenizer.apply_chat_template(
    messages,
    tokenize=True,
    add_generation_prompt=True,
    return_tensors="pt"
).to("cuda")

outputs = model.generate(
    input_ids=inputs,
    max_new_tokens=300,
    temperature=0.7,
    top_p=0.9,
)

print(tokenizer.decode(outputs[0]))

# тестирование по 10 запросов на одну тему
prompts = [
    "Напиши текст в научном стиле. Тема: Квантовые вычисления",
    "Напиши текст в научном стиле. Тема: Теория графов ",
    "Напиши текст в научном стиле. Тема: Генетические мутации ",
    "Напиши текст в научном стиле. Тема: Черные дыры",
    "Напиши текст в научном стиле. Тема: Термодинамика ",
    "Напиши текст в научном стиле. Тема: Нанотехнологии"

]

for prompt in prompts:
    messages = [{"role": "user", "content": prompt}]

    inputs = tokenizer.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=True,
        return_tensors="pt"
    ).to("cuda")

    outputs = model.generate(
        input_ids=inputs,
        max_new_tokens=300,
        temperature=0.7,
        top_p=0.9,
        repetition_penalty = 1.1,
        no_repeat_ngram_size = 2
    )

    print("\n=== PROMPT ===")
    print(prompt)
    print("=== OUTPUT ===")
    print(tokenizer.decode(outputs[0]))

prompts = [
    "Напиши текст в публицистическом стиле. Тема: Глобальное потепление",
    "Напиши текст в публицистическом стиле. Тема: Фотосинтез",
    "Напиши текст в публицистическом стиле. Тема: Вечер перед бурей",
    "Напиши текст в публицистическом стиле. Тема: Развитие искусственного интеллекта",
    "Напиши текст в публицистическом стиле. Тема: Рост цен на продукты",
    "Напиши текст в публицистическом стиле. Тема: Влияние социальных сетей на общество",
    "Напиши текст в публицистическом стиле. Тема: Проблема загрязнения океанов",
    "Напиши текст в публицистическом стиле. Тема: Удалённая работа: плюсы и минусы",
    "Напиши текст в публицистическом стиле. Тема: Кризис образования",
    "Напиши текст в публицистическом стиле. Тема: Массовая урбанизация"

]

prompts = [
    "Напиши текст в научном стиле. Тема: Квантовые вычисления",
    "Напиши текст в научном стиле. Тема: Теория графов ",
    "Напиши текст в научном стиле. Тема: Генетические мутации ",
    "Напиши текст в научном стиле. Тема: Черные дыры",
    "Напиши текст в научном стиле. Тема: Термодинамика ",
    "Напиши текст в научном стиле. Тема: Нанотехнологии"

]