# -*- coding: utf-8 -*-
"""Тест phi-3-mini.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15lgkbQ2UPKXrNpg4ujpYBdLP3NSlU6W9
"""

!pip install torch --upgrade
!pip install transformers==4.41.2 accelerate sentencepiece

!pip uninstall -y requests huggingface_hub transformers
!pip install requests==2.31.0
!pip install huggingface_hub==0.23.5
!pip install transformers==4.41.2

# тест одного запроса
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

model_id = "microsoft/Phi-3-mini-4k-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_id)

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    device_map="auto",
    trust_remote_code=True,
    torch_dtype=torch.float16
)

prompt = "Напиши текст в художественном стиле. Тема: Глобальное потепление"

# ВАЖНО: используем chat template
messages = [
    {"role": "user", "content": prompt}
]

inputs = tokenizer.apply_chat_template(
    messages,
    return_tensors="pt",
    add_generation_prompt=True
).to(model.device)

outputs = model.generate(
    input_ids=inputs,
    max_new_tokens=300,
    do_sample=True,
    top_p=0.9,
    temperature=0.7
)

print(tokenizer.decode(outputs[0], skip_special_tokens=True))

# тестирование сразу на 10 запросов батчем
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

model_id = "microsoft/Phi-3-mini-4k-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_id)

# Добавляем pad_token если его нет
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    device_map="auto",
    trust_remote_code=True,
    torch_dtype=torch.float16
)

prompts = [
    "Напиши текст в научном стиле. Тема: Глобальное потепление",
    "Напиши текст в научном стиле. Тема: Фотосинтез",
    "Напиши текст в научном стиле. Тема: Вечер перед бурей",
    "Напиши текст в научном стиле. Тема: Развитие искусственного интеллекта",
    "Напиши текст в научном стиле. Тема: Квантовые вычислени",
    "Напиши текст в научном стиле. Тема: Теория графов",
    "Напиши текст в научном стиле. Тема: Черные дыры",
    "Напиши текст в научном стиле. Тема: Нанотехнологии",
    "Напиши текст в научном стиле. Тема: Термодинамика",
    "Напиши текст в научном стиле. Тема: Генетические мутации "
]

# Форматируем каждый промпт с шаблоном чата
formatted_prompts = []
for prompt in prompts:
    messages = [{"role": "user", "content": prompt}]
    formatted = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )
    formatted_prompts.append(formatted)

# Батч токенизация
inputs = tokenizer(
    formatted_prompts,
    return_tensors="pt",
    padding=True,
    truncation=True,
    max_length=2048
).to(model.device)

# Генерация
outputs = model.generate(
    **inputs,
    max_new_tokens=300,
    do_sample=True,
    temperature=0.7,
    pad_token_id=tokenizer.pad_token_id,
    eos_token_id=tokenizer.eos_token_id
)

# Декодирование всех ответов
decoded_outputs = tokenizer.batch_decode(outputs, skip_special_tokens=True)

# Печать
for i, output in enumerate(decoded_outputs):
    print(f"\n=== Ответ {i+1} ===")
    print(output)
    print("-" * 50)